// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetEventsIDOKCode is the HTTP code returned for type GetEventsIDOK
const GetEventsIDOKCode int = 200

/*GetEventsIDOK Retrieved

swagger:response getEventsIdOK
*/
type GetEventsIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetEventsIDOKBody `json:"body,omitempty"`
}

// NewGetEventsIDOK creates GetEventsIDOK with default headers values
func NewGetEventsIDOK() *GetEventsIDOK {

	return &GetEventsIDOK{}
}

// WithPayload adds the payload to the get events Id o k response
func (o *GetEventsIDOK) WithPayload(payload *GetEventsIDOKBody) *GetEventsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get events Id o k response
func (o *GetEventsIDOK) SetPayload(payload *GetEventsIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEventsIDNotFoundCode is the HTTP code returned for type GetEventsIDNotFound
const GetEventsIDNotFoundCode int = 404

/*GetEventsIDNotFound Not Found

swagger:response getEventsIdNotFound
*/
type GetEventsIDNotFound struct {
}

// NewGetEventsIDNotFound creates GetEventsIDNotFound with default headers values
func NewGetEventsIDNotFound() *GetEventsIDNotFound {

	return &GetEventsIDNotFound{}
}

// WriteResponse to the client
func (o *GetEventsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
