// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetEventHandlerFunc turns a function with the right signature into a get event handler
type GetEventHandlerFunc func(GetEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventHandlerFunc) Handle(params GetEventParams) middleware.Responder {
	return fn(params)
}

// GetEventHandler interface for that can handle valid get event params
type GetEventHandler interface {
	Handle(GetEventParams) middleware.Responder
}

// NewGetEvent creates a new http.Handler for the get event operation
func NewGetEvent(ctx *middleware.Context, handler GetEventHandler) *GetEvent {
	return &GetEvent{Context: ctx, Handler: handler}
}

/* GetEvent swagger:route GET /event getEvent

request an event

*/
type GetEvent struct {
	Context *middleware.Context
	Handler GetEventHandler
}

func (o *GetEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetEventAcceptedBody get event accepted body
//
// swagger:model GetEventAcceptedBody
type GetEventAcceptedBody struct {

	// foo
	ID int64 `json:"id,omitempty"`
}

// Validate validates this get event accepted body
func (o *GetEventAcceptedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get event accepted body based on context it is used
func (o *GetEventAcceptedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetEventAcceptedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetEventAcceptedBody) UnmarshalBinary(b []byte) error {
	var res GetEventAcceptedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
